import { ASTBuilder } from './codegen/ast-builder';
import { ASTGenerator } from './codegen/ast-generator';

const b = new ASTBuilder();

const ast = b.root(
  b.package('RoboticsModel',
    b.doc('A model for robotic systems'),

    b.abstractClass('Component',
      b.feature('id', { typings: ['Integer'] }),
      b.feature('name', { typings: ['String'], multiplicity: [0, 1] }),
    ),

    b.class('Sensor', { specializations: ['Component'] },
      b.feature('sampleRate', { typings: ['Real'], isReadonly: true }),
      b.feature('data', { typings: ['SensorData'], direction: 'out', multiplicity: [0, '*'] }),
    ),

    b.class('Actuator', { specializations: ['Component'] },
      b.feature('command', { typings: ['Command'], direction: 'in' }),
      b.feature('maxTorque', { typings: ['Real'] }),
    ),

    b.class('Robot',
      b.part('sensors', 'Sensor', { multiplicity: [1, '*'] }),
      b.part('actuators', 'Actuator', { multiplicity: [1, '*'] }),
      b.port('controlPort', 'ControlInterface'),
    ),

    b.datatype('Real'),
    b.datatype('Integer'),
    b.datatype('String'),
    b.datatype('SensorData'),
    b.datatype('Command'),
    b.datatype('ControlInterface'),

    b.enum('RobotState', 'idle', 'moving', 'error', 'charging'),

    b.assoc('SensorLink', {},
      b.endFeature('robot', 'Robot'),
      b.endFeature('sensor', 'Sensor', { multiplicity: [1, '*'] }),
    ),

    b.behavior('Navigate', [
      b.inFeature('destination', 'String'),
      b.outFeature('arrived', 'Boolean'),
    ]),

    b.func('calculateDistance', [
      b.inFeature('from', 'Position'),
      b.inFeature('to', 'Position'),
    ], 'Real'),

    b.predicate('isReachable', [
      b.inFeature('target', 'Position'),
    ]),

    b.connector('sensorBus', 'Robot::sensors', 'Robot::controlPort'),

    b.succession('Sensor::data', 'Actuator::command'),

    b.metaclass('SafetyCritical'),

    b.metadata('SafetyCritical', ['Robot']),

    b.comment('Main robot model for autonomous navigation', ['Robot']),
  ),
);

const generator = new ASTGenerator({
  headerComment: 'Generated by KerML AST Builder',
});

console.log(generator.generate(ast));